version: "1.0"
info:
  model: int-scaffold
packages:
- name: IWHIB2BHolProject
  gitServerName: github_prudhvi
  gitUrl: https://github.com/prudhvi-penmetsa-saggs
  gitUsername: prudhvi-penmetsa-saggs
  gitBranch: main
services:
- serviceName: project.iwhib2bhol.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:getTaxRate
  packages:
  - name: IWHIB2BHolProject
    version: "1.0"
- serviceName: project.iwhib2bhol.integrations:calculateSalesTax
  packages:
  - name: IWHIB2BHolProject
    version: "1.0"
- serviceName: pub.math:multiplyFloats
  packages:
  - name: WmPublic
    version: 12.1.0.0.828
- serviceName: pub.math:divideFloats
  packages:
  - name: WmPublic
    version: 12.1.0.0.828
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 12.1.0.0.828
